services:
  
  stream-orig:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
    volumes:
      - shared-volume:/recordings
      - ./k8s/mediamtx.yml:/mediamtx.yml
  
  # stream-360p:
  #   image: bluenviron/mediamtx:latest-ffmpeg
  #   ports:
  #     - 2935:2935
  #     - 7554:7554
  #     - 7888:7888
  #   volumes:
  #     - shared-volume:/recordings
  #     - ./k8s/mediamtx-360p.yml:/mediamtx.yml
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 4000:4000
      - 5555:5555
    volumes:
      - shared-volume:/app/recordings
      - upload-volume:/app/uploads
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - REDIS_URL=redis://redis:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      # - stream-orig
      - backend
    ports:
      - 8080:8080
    volumes:
      - shared-volume:/app/dist/recordings
      - upload-volume:/app/dist/uploads

volumes:
  shared-volume:
    name: shared-data
  upload-volume:
    name: upload-data
  redis-volume:
    name: redis-data
