version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  
  stream:
    image: bluenviron/mediamtx:latest
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
      - 8889:8889
