services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 5555:5555
    volumes:
      - shared-volume:/app/recordings
      - upload-volume:/app/uploads
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      # - stream-orig
      - backend
    ports:
      - 8080:8080
    volumes:
      - shared-volume:/app/dist/recordings
      - upload-volume:/app/dist/uploads
  
  # stream-orig:
  #   image: bluenviron/mediamtx:latest-ffmpeg
  #   ports:
  #     - 1935:1935
  #     - 8554:8554
  #     - 8888:8888
  #   volumes:
  #     - shared-volume:/recordings
  #     - ./k8s/mediamtx.yml:/mediamtx.yml
  
  # stream-360p:
  #   image: bluenviron/mediamtx:latest-ffmpeg
  #   ports:
  #     - 2935:2935
  #     - 7554:7554
  #     - 7888:7888
  #   volumes:
  #     - shared-volume:/recordings
  #     - ./k8s/mediamtx-360p.yml:/mediamtx.yml

volumes:
  shared-volume:
    name: shared-data
  upload-volume:
    name: upload-data
