version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 5555:5555
    volumes:
      - shared-volume:/app/recordings
      - ./backend/prisma/dev.db:/app/prisma/dev.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - stream-orig
      - backend
    ports:
      - 8080:8080
    volumes:
      - shared-volume:/app/dist/recordings
  
  stream-orig:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
      - 8889:8889
      - 9997:9997
      - 9998:9998
    volumes:
      - shared-volume:/recordings
      - ./k8s/mediamtx.yml:/mediamtx.yml
  
  # stream-360p:
  #   image: bluenviron/mediamtx:latest-ffmpeg
  #   ports:
  #     - 1935:1935
  #     - 8554:8554
  #     - 8888:8888
  #     - 8889:8889
  #   volumes:
  #     - shared-volume:/recordings
  #     - ./k8s/mediamtx-360p.yml:/mediamtx.yml

volumes:
  shared-volume:
    name: shared-data
