version: '3'
services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - shared-volume:/recordings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - shared-volume:/app/dist/recordings
  
  stream:
    image: bluenviron/mediamtx:latest
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
      - 8889:8889
    volumes:
      - shared-volume:/recordings
      - ./k8s/mediamtx.yml:/mediamtx.yml

volumes:
  shared-volume:
    name: shared-data
