services:
  
  stream-orig:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - 1935:1935
      - 8554:8554
      - 8888:8888
    volumes:
      - shared-volume:/recordings
      - ./k8s/configs/mediamtx.yml:/mediamtx.yml
  
  stream-360p:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - 2935:2935
      - 7554:7554
      - 7888:7888
    volumes:
      - shared-volume:/recordings
      - ./k8s/configs/mediamtx-360p.yml:/mediamtx.yml
  
  stream-720p:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - 3935:3935
      - 6554:6554
      - 6888:6888
    volumes:
      - shared-volume:/recordings
      - ./k8s/configs/mediamtx-720p.yml:/mediamtx.yml
  
  stream-1080p:
    image: bluenviron/mediamtx:latest-ffmpeg
    ports:
      - 4935:4935
      - 5554:5554
      - 5888:5888
    volumes:
      - shared-volume:/recordings
      - ./k8s/configs/mediamtx-1080p.yml:/mediamtx.yml
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data

  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    volumes:
      - cockroachdb-volume:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8090:8080"
    environment:
      - COCKROACHDB_USER=root
      - COCKROACHDB_PASSWORD=root
    restart: unless-stopped
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 4000:4000
      - 5555:5555
    volumes:
      - shared-volume:/app/recordings
      - upload-volume:/app/uploads
      - ./backend/prisma/dev.db:/app/prisma/dev.db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://root@cockroachdb:26257/streamify?sslmode=disable
      REDIS_URL: redis://redis:6379
      HYPERDX_API_KEY: ${HYPERDX_API_KEY}
      OTEL_SERVICE_NAME: streamify-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - stream-orig
      - backend
    ports:
      - 8080:8080
    volumes:
      - shared-volume:/app/dist/recordings
      - upload-volume:/app/dist/uploads

volumes:
  shared-volume:
    name: shared-data
  upload-volume:
    name: upload-data
  redis-volume:
    name: redis-data
  cockroachdb-volume:
    name: cockroachdb-data
