apiVersion: v1
kind: Service
metadata:
    name: mediamtx-service
spec:
    selector:
        app: mediamtx
    ports:
        - name: rtmp
          protocol: TCP
          port: 1935
          targetPort: 1935
        - name: rtsp
          protocol: TCP
          port: 8554
          targetPort: 8554
        - name: hls
          protocol: TCP
          port: 8888
          targetPort: 8888
        - name: webrtc
          protocol: TCP
          port: 8889
          targetPort: 8889
    type: LoadBalancer
