apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      labels:
        app: stream
    spec:
      containers:
        - name: stream
          image: bluenviron/mediamtx:latest
          volumeMounts:
            - name: shared-volume
              mountPath: /recordings
            - name: config-volume
              mountPath: /mediamtx.yml
              subPath: mediamtx.yml
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: stream-config
