apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: msokolik55/frontend:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: recordings
              mountPath: /app/dist/recordings
            - name: uploads
              mountPath: /app/dist/uploads
      volumes:
        - name: recordings
          persistentVolumeClaim:
            claimName: shared-data-pvc
        - name: uploads
          persistentVolumeClaim:
            claimName: upload-data-pvc
