apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-1080p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-1080p
  template:
    metadata:
      labels:
        app: stream-1080p
    spec:
      containers:
        - name: stream-1080p
          image: bluenviron/mediamtx:latest-ffmpeg
          ports:
            - containerPort: 4935
            - containerPort: 5554
            - containerPort: 5888
          volumeMounts:
            - name: shared-volume
              mountPath: /recordings
            - name: config-volume
              mountPath: /mediamtx.yml
              subPath: mediamtx.yml
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
        - name: config-volume
          configMap:
            name: stream-1080p-config
