apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-orig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-orig
  template:
    metadata:
      labels:
        app: stream-orig
    spec:
      containers:
        - name: stream-orig
          image: bluenviron/mediamtx:latest
          ports:
            - containerPort: 1935
            - containerPort: 8554
            - containerPort: 8888
          volumeMounts:
            - name: shared-volume
              mountPath: /recordings
            - name: config-volume
              mountPath: /mediamtx.yml
              subPath: mediamtx.yml
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
        - name: config-volume
          configMap:
            name: stream-config
