apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-360p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-360p
  template:
    metadata:
      labels:
        app: stream-360p
    spec:
      containers:
        - name: stream-360p
          image: bluenviron/mediamtx:latest-ffmpeg
          ports:
            - containerPort: 2935
            - containerPort: 7554
            - containerPort: 7888
          volumeMounts:
            - name: shared-volume
              mountPath: /recordings
            - name: config-volume
              mountPath: /mediamtx.yml
              subPath: mediamtx.yml
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-data-pvc
        - name: config-volume
          configMap:
            name: stream-360p-config
