apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
    - name: prisma-studio
      port: 5555
      targetPort: 5555
