apiVersion: v1
kind: Service
metadata:
  name: stream-orig
spec:
  type: LoadBalancer
  selector:
    app: stream-orig
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: rtsp
      protocol: TCP
      port: 8554
      targetPort: 8554
    - name: hls
      protocol: TCP
      port: 8888
      targetPort: 8888
